### PR TITLE
Legit branch

### PR DESCRIPTION
**Pull request by segg21**
I have added a config change command to EssentialCommands

I have tested before published, but confirm this is how it supposed to be.

@Andrews54757

### CODE REVIEW

**Comment by segg21** [comment]
@Andrews54757 Found a bug i'm not to sure how to fix.

You can change the value once, but if you try to change it again it doesn't exist.

**Comment by segg21** [comment]
Actually I change my mind, it doesn't work. I was going based on the log, but if you change the config, the game no longer works. Are you not supposed to change config values?

**Comment by Andrews54757** [comment]
@LegitSoulja You made a mistake. Line 6 of change.js

**Comment by Andrews54757** [comment]
@LegitSoulja Fixed it for you

**Comment by segg21** [comment]
Oops

**Comment by segg21** [comment]
Shall I implement more commands that was in ogarul?

**Comment by Andrews54757** [comment]
Why not? Go ahead. Also, I am amused at a server at http://forum.ogarul.io/pages/OAStats/. They did http://opnagar.us/server/http://agartest. Wow

**Comment by Andrews54757** [comment]
I will have to now add a exception so it allows http://agartest

**Comment by segg21** [comment]
@Andrews54757 lol wow, I guess the instructions wasn't as clear

**Comment by segg21** [comment]
Merging this, and i'll merge the rest later.

**Comment by Andrews54757** [comment]
Fixed http://opnagar.us/server/http://agartest

**Comment by Andrews54757** [comment]
Wow, openagar is soo smooth

**Comment by segg21** [comment]
@Andrews54757 oops, lol, I forgot about the plugin compression/converter thing.

**Comment by segg21** [comment]
It can wait till the next merge lol

**Comment by segg21** [comment]
@Andrews54757 I got a question. I want to bring MassStart and IpBots to OpenAgar, but the thing is that they both creates a json file, in which stores content of players ip to defined values when they join and etc.

How can I accomplish this? 

Im also thinking about creating a database plugin in which will send, and receive data from mysql. Not our database, but a database that can be used for whatever use.

Which means, another site, in which the server owner can register, get a specific key to store there own server data within it, from plugin configs. The database plugin will basically be an api for other plugins usages. What do you think?

**Comment by Andrews54757** [comment]
@LegitSoulja I need help. OAStats for the forums are not displaying properly when there are two servers

**Comment by Andrews54757** [comment]
Fixed

**Comment by segg21** [comment]
@Andrews54757 Sorry I wasn't here earlier, glad it's fixed.

**Comment by Andrews54757** [comment]
@LegitSoulja I need help again. The logo isnt sent fully

**Comment by Andrews54757** [comment]
@LegitSoulja Could you check the logo column at oastats? (sql). Whats the datatype and limit?

**Comment by LegitSoulja** [comment]
@Andrews54757 

capture

**Comment by LegitSoulja** [comment]
capture

**Comment by Andrews54757** [comment]
What does longtext mean?

**Comment by Andrews54757** [comment]
@LegitSoulja How come the full logo url isnt sent?

**Comment by segg21** [comment]
I changed it, since you're using json.

LongText has a length of 4million char length

**Comment by segg21** [comment]
What do you mean the full logo?

**Comment by Andrews54757** [comment]
The url for the logo is cut short whenever you register a server,

**Comment by segg21** [comment]
Let me remove the default lengths.

**Comment by Andrews54757** [comment]
?

**Comment by segg21** [comment]
Do me a favor, and start the server again so that the row will be created again

**Comment by Andrews54757** [comment]
It works! How?

**Comment by segg21** [comment]
The data lengths

**Comment by segg21** [comment]
for logo, the length was 15

**Comment by Andrews54757** [comment]
It says it is 100

**Comment by segg21** [comment]
Yea, I changed it

**Comment by Andrews54757** [comment]
Okay

**Comment by segg21** [comment]
It can be null, or higher than what was set as default.

**Comment by Andrews54757** [comment]
I am hosting a server for OpenAgar that has every completed gamemode running

**Comment by LegitSoulja** [comment]
@Andrews54757 After configured

capture

**Comment by segg21** [comment]
for some reason, I can't leave a blank length/set when using varchar. weird.

**Comment by Andrews54757** [comment]
Okay, I deleted your table images though for security

**Comment by segg21** [comment]
@Andrews54757 Now,

Since I know you have your own sql client, which I know you can't use because of connection privacy, but I have added your ip to the remote mysql access, so you should be able to use it now.

And what do you mean you delete my table images?

**Comment by segg21** [comment]
Oh nvm, I know what you mean about images.

**Comment by segg21** [comment]
@Andrews54757 I'll be on gitter if you need me again.

**Comment by Andrews54757** [comment]
I am running my server on a virtual machine

screen shot 2017-01-08 at 9 11 21 pm

**Comment by segg21** [comment]
That's all? for 5 servers? Im shocked.

**Comment by Andrews54757** [comment]
Yeah

**Comment by segg21** [comment]
@Andrews54757 im gonna host one now :)

**Comment by Andrews54757** [comment]
CPU now dropped to 5. V8 has probably optimised

**Comment by segg21** [comment]
My server should be up now

**Comment by Andrews54757** [comment]
It is

**Pull request merged**
